// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// picrust_otu
List picrust_otu(std::string file_path, StringVector otu_id_targets);
RcppExport SEXP _themetagenomics_picrust_otu(SEXP file_pathSEXP, SEXP otu_id_targetsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type file_path(file_pathSEXP);
    Rcpp::traits::input_parameter< StringVector >::type otu_id_targets(otu_id_targetsSEXP);
    rcpp_result_gen = Rcpp::wrap(picrust_otu(file_path, otu_id_targets));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_themetagenomics_picrust_otu", (DL_FUNC) &_themetagenomics_picrust_otu, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_themetagenomics(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
