// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// picrust
List picrust(std::string file_path, StringVector otu_id_targets);
RcppExport SEXP themetagenomics_picrust(SEXP file_pathSEXP, SEXP otu_id_targetsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type file_path(file_pathSEXP);
    Rcpp::traits::input_parameter< StringVector >::type otu_id_targets(otu_id_targetsSEXP);
    rcpp_result_gen = Rcpp::wrap(picrust(file_path, otu_id_targets));
    return rcpp_result_gen;
END_RCPP
}
