#' @import lme4 rstan Rcpp
#' @importFrom stats4 summary
#' @importFrom stats predict as.formula cor cov rnorm model.frame quantile relevel terms
NULL

#' Estimate topic or function effects
#'
#' @param object A topics or functions object generated by \code{\link{find_topics}} or \code{\link{predict}}, respectively.
#' @param ... Additional arguments for methods.
#'
#' @seealso \code{\link{est.topics}} \code{\link{est.functions}} \code{\link{est.hmc}} \code{\link{est.ml}}
#'
#' @export
est <- function(object,...) UseMethod('est')
