#' Estimate topic or function effects
#'
#' @param object A topics or functions object generated by \code{\link{find_topics}} or \code{\link{topics.predict}}, respectively.
#' @param ... Additional arguments for methods.
#' @examples
#' topics <- find_topics(K=30,otu_table=otu_table,rows_are_taxa=FALSE,formula=group + time,metadata=metadata,refs=c('A'))
#' topic_effects <- est(topics,metadata=metadata,formula=~group + time,refs=c('A'),moderator='group')
#'
#' download_ref('~/references')
#' functions <- predict(topics,reference_path='~/references/ko_13_5_precalculated.tab.gz',scalar=100)
#' function_effects <- est(functions,level=2,method='HMC')
#' @export
est <- function(object,...) UseMethod('est')

#' Print summary for effects class resulting from topics
#' @export
print.effects <- function(effects_object,...){
  cat(sprintf('An %s object containing topic model effects information.\n',class(effects_object)))

  cat(sprintf('\n%s total covariate(s):\n',ncol(effects_object$modelframe)))
  mf <- effects_object$modelframe
  for (i in seq_len(ncol(effects_object$modelframe))){
    cl <- class(mf[[i]])
    if (cl == 'numeric'){
      cat(sprintf('%s\t%s (mean=%.02f, median=%.02f, std=%.02f)\n',
                  cl,
                  colnames(mf)[i],
                  mean(mf[[i]]),median(mf[[i]]),sd(mf[[i]])))
    }else{
      cat(sprintf('%s\t%s (N=%s, N+=%s)\n',
                  cl,
                  colnames(mf)[i],
                  length(mf[[i]]),
                  sum(mf[[i]] == levels(mf[[i]])[2])))
    }
  }

  cat(sprintf('\nTopic weights outside %s-%s uncertainty interval:\n',
              colnames(effects_object$topic_effects[[1]]$est)[2],
              colnames(effects_object$topic_effects[[1]]$est)[3]))
  for (i in seq_len(ncol(effects_object$modelframe))){
    sig_topics <- effects_object$topic_effects[[i]]$sig
    if (length(sig_topics) > 0){
      cat(sprintf('%s:\t%s\n',
                  colnames(mf)[i],
                  paste0('T',sig_topics,collapse=' ')))
    }else{
      cat(sprintf('%s:\t%s\n',
                  colnames(mf)[i],
                  ''))
    }
  }
}

#' Print summary for effects class resulting from functions
#' @export
print.functions <- function(functions_object,...){
  # placeholder
}

#' Prevent object renaming in class effects
#' @export
`names<-.effects` <- function(object,value){
  warning('effects-class objects cannot be renamed.')
  return(object)
}

#' Prevent attribute renaming in class topics
#' @export
`attributes<-.effects` <- function(object,value){
  warning('effects-class attributes cannot be renamed.')
  return(object)
}
