#' @import lme4 rstan Rcpp
#' @importFrom stats4 summary
NULL

#' Estimate topic or function effects
#'
#' @param object A topics or functions object generated by \code{\link{find_topics}} or \code{\link{predict}}, respectively.
#' @param ... Additional arguments for methods.
#'
#' @seealso \code{\link{est.topics}} \code{\link{est.functions}} \code{\link{fit_hmc}} \code{\link{fit_ml}}
#'
#' @export
est <- function(object,...) UseMethod('est')
