# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Predict functional potential
#'
#' This predicts the functional potential of a topic metagenome.
#' Raw OTU tables may be used as well. By default, the function
#' uses PICRUSt's precalculated GreenGreens table. If the user
#' chooses to provide his or her own, then the table must be
#' formatted accordingly.
#'
#' @param file_path Path to the precalculated table
#' @param otu_id_targets Character vector of OTU IDs to predict
#' @return A list containing the the gene IDs, the OTU IDs that
#' were present in the precalculated table and hence predicted,
#' the PICRUSt gene metadata, the predicted gene table, and the
#' PICRUSt metadata that contains confidence scores, etc.
#' @export
picrust <- function(file_path, otu_id_targets) {
    .Call('themetagenomics_picrust', PACKAGE = 'themetagenomics', file_path, otu_id_targets)
}

