#' Visualize effects object with Shiny
#'
#' @aliases vis.topics
#' @param effects_object An object of class effects, generated by \code{\link{est}}.
#' @param tax_table Taxonomic table associated with otu_table used in \code{\link{find_topics}}.
#' @param type Type of visualization to perform.
#' @param ... Additional arguments for methods.
#' @examples
#' topics <- find_topics(K=30,otu_table=otu_table,rows_are_taxa=FALSE,formula=group + time,metadata=metadata,refs=c('A'))
#'
#' topic_effects <- est(topics,metadata=metadata,formula=~group + time,refs=c('A'),moderator='group')
#'
#' vis(topic_effects,taxa=taxa_table,type='topic')
#' vis(topic_effects,taxa=taxa_table,type='binary')
#' vis(topic_effects,taxa=taxa_table,type='continuous',moderator='group')
#' @export
vis <- function(effects_object,tax_table,type=c('topic','binary','continuous','function'),...) UseMethod('vis')

#' @export
vis.effects <- function(effects_object,tax_table,type=c('topic','binary','continuous','function'),...){
  type <- match.arg(type)

  if (type == 'topic'){
    vis_topic_features(topics=effects_object$topics,
                       topic_effects=effects_object,
                       taxa=tax_table,...)
  }else if (type == 'binary'){
    vis_covariate_effects_binary(topics=effects_object$topics,
                                 topic_effects=effects_object,
                                 otu_table=effects_object$topics$otu_table,
                                 taxa=tax_table,...)
  }else if (type == 'continuous'){
    vis_covariate_effects_continuous(topics=effects_object$topics,
                                     topic_effects=effects_object,
                                     otu_table=effects_object$topics$otu_table,
                                     taxa=tax_table,...)
  }else{
    vis_function_effects(topics=effects_object$topics,
                         topic_effects=effects_object,
                         function_effects=effects_object$functions,
                         taxa=tax_table,...)
  }
}
